### ISSUE TITLE
ChipWhisperer project

### ISSUE THREAD

**Issue by ghost** [ANSSI-FR/SecAESSTM32#2]
Thanks for that very interesting effort.  
Could you add the CW project you used for the side-channel characterization? It would be a major help for people who want to directly use this work for educational purpose.

**Comment by rben-dev** [comment]
Hi,

Thanks for your interest in the project ! Although we have used the CW CW308T-STM32F  target board for our characterization, we have not created a CW project per se.

In order to achieve good sampling rates and since we had oscilloscopes available, we have plugged the CW consumption SMA connector directly to the oscilloscope. Then, we simply used a trigger through a GPIO to synchronize our acquisitions and drive the oscilloscope.

Creating a CW specific project is consequently left as a "to do" for the people interested in using the complete CW toolchain, e.g. for educational purpose.

Regards,
